name: Create GitHub Release

on:
  push:
    tags: ['v*']
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  release:
    uses: xibo-players/.github/.github/workflows/create-release.yml@e54c80aa9c5a89decd9f978f082047759eddf705  # main
    with:
      package-name: arexibo
      description: 'Minimal native Xibo digital signage player written in Rust.'
